### ISSUE TITLE
ButtonsPanelHelper need to be implemented ?

### ISSUE THREAD

**Issue by genthalili** [balvi/cuba-example-declarative-comments#2]
Is it necessary to implement this class?

https://github.com/balvi/cuba-example-declarative-comments/blob/master/modules/web/src/de/balvi/cuba/example/declarativecomments/web/commentable/ButtonsPanelHelper.groovy

**Comment by mariodavid** [comment]
hi,

no, its not. I think this was my initial misunderstanding when misusing studio when I added the dependency. Here's a corresponding issue for studio: https://youtrack.cuba-platform.com/issue/STUDIO-4561

It can just be deleted in here, because it is already in declarative-controllers

**Comment by genthalili** [comment]
Thanks @mariodavid! 
This can be fixed by `dependsOn ` in `app-component.xml`of `<app-component>` balise, so after this, there is no need to implement on your project.
